# settings and constants

LOW_QUALITY_PATH = "./audio_lq/"
HIGH_QUALITY_PATH = "./audio_hq/"
VAL_LQ = "./val_lq/"
VAL_HQ = "./val_hq/"
TEST_DATA_LQ = "./final_lq/"
TEST_DATA_HQ = "./final_hq/"

LQ_SAMPLE_RATE = 8000
HQ_SAMPLE_RATE = 48000

PERCENT_OF_DATA_TO_TRAIN = 80
PERCENT_OF_DATA_TO_VALIDATE = 10
PERCENT_OF_DATA_TO_TEST = 10
NUM_WORKERS = 4

BATCH_SIZE = 4
LEARNING_RATE = 0.005
EPOCHS = 4

INPUT_SIZE = 1
OUTPUT_SIZE = 1
# EMB_SIZE = 1000
HIDDEN_SIZE = 8
N_LAYERS = 2
ENC_DROPOUT = 0.5
DEC_DROPOUT = 0.5